/*
ETSI ISG CIM / NGSI-LD API

This OAS file describes the NGSI-LD API defined by the ETSI ISG CIM group. This Cross-domain Context Information Management API allows to provide, consume and subscribe to context information in multiple scenarios and involving multiple stakeholders

API version: latest
Contact: NGSI-LD@etsi.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// ContextSourceRegistration struct for ContextSourceRegistration
type ContextSourceRegistration struct {
	Context map[string]interface{} `json:"@context,omitempty"`
	Information []RegistrationInfo `json:"information"`
	ObservationInterval *TimeInterval `json:"observationInterval,omitempty"`
	ManagementInterval *TimeInterval `json:"managementInterval,omitempty"`
	Location *Geometry `json:"location,omitempty"`
	ObservationSpace *Geometry `json:"observationSpace,omitempty"`
	OperationSpace *Geometry `json:"operationSpace,omitempty"`
	Expires *time.Time `json:"expires,omitempty"`
	Name *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Endpoint string `json:"endpoint"`
	Id string `json:"id"`
	Type string `json:"type"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	ModifiedAt *time.Time `json:"modifiedAt,omitempty"`
}

// NewContextSourceRegistration instantiates a new ContextSourceRegistration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContextSourceRegistration(information []RegistrationInfo, endpoint string, id string, type_ string) *ContextSourceRegistration {
	this := ContextSourceRegistration{}
	this.Information = information
	this.Endpoint = endpoint
	this.Id = id
	this.Type = type_
	return &this
}

// NewContextSourceRegistrationWithDefaults instantiates a new ContextSourceRegistration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContextSourceRegistrationWithDefaults() *ContextSourceRegistration {
	this := ContextSourceRegistration{}
	return &this
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *ContextSourceRegistration) GetContext() map[string]interface{} {
	if o == nil || o.Context == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContextSourceRegistration) GetContextOk() (map[string]interface{}, bool) {
	if o == nil || o.Context == nil {
		return nil, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *ContextSourceRegistration) HasContext() bool {
	if o != nil && o.Context != nil {
		return true
	}

	return false
}

// SetContext gets a reference to the given map[string]interface{} and assigns it to the Context field.
func (o *ContextSourceRegistration) SetContext(v map[string]interface{}) {
	o.Context = v
}

// GetInformation returns the Information field value
func (o *ContextSourceRegistration) GetInformation() []RegistrationInfo {
	if o == nil {
		var ret []RegistrationInfo
		return ret
	}

	return o.Information
}

// GetInformationOk returns a tuple with the Information field value
// and a boolean to check if the value has been set.
func (o *ContextSourceRegistration) GetInformationOk() ([]RegistrationInfo, bool) {
	if o == nil {
		return nil, false
	}
	return o.Information, true
}

// SetInformation sets field value
func (o *ContextSourceRegistration) SetInformation(v []RegistrationInfo) {
	o.Information = v
}

// GetObservationInterval returns the ObservationInterval field value if set, zero value otherwise.
func (o *ContextSourceRegistration) GetObservationInterval() TimeInterval {
	if o == nil || o.ObservationInterval == nil {
		var ret TimeInterval
		return ret
	}
	return *o.ObservationInterval
}

// GetObservationIntervalOk returns a tuple with the ObservationInterval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContextSourceRegistration) GetObservationIntervalOk() (*TimeInterval, bool) {
	if o == nil || o.ObservationInterval == nil {
		return nil, false
	}
	return o.ObservationInterval, true
}

// HasObservationInterval returns a boolean if a field has been set.
func (o *ContextSourceRegistration) HasObservationInterval() bool {
	if o != nil && o.ObservationInterval != nil {
		return true
	}

	return false
}

// SetObservationInterval gets a reference to the given TimeInterval and assigns it to the ObservationInterval field.
func (o *ContextSourceRegistration) SetObservationInterval(v TimeInterval) {
	o.ObservationInterval = &v
}

// GetManagementInterval returns the ManagementInterval field value if set, zero value otherwise.
func (o *ContextSourceRegistration) GetManagementInterval() TimeInterval {
	if o == nil || o.ManagementInterval == nil {
		var ret TimeInterval
		return ret
	}
	return *o.ManagementInterval
}

// GetManagementIntervalOk returns a tuple with the ManagementInterval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContextSourceRegistration) GetManagementIntervalOk() (*TimeInterval, bool) {
	if o == nil || o.ManagementInterval == nil {
		return nil, false
	}
	return o.ManagementInterval, true
}

// HasManagementInterval returns a boolean if a field has been set.
func (o *ContextSourceRegistration) HasManagementInterval() bool {
	if o != nil && o.ManagementInterval != nil {
		return true
	}

	return false
}

// SetManagementInterval gets a reference to the given TimeInterval and assigns it to the ManagementInterval field.
func (o *ContextSourceRegistration) SetManagementInterval(v TimeInterval) {
	o.ManagementInterval = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *ContextSourceRegistration) GetLocation() Geometry {
	if o == nil || o.Location == nil {
		var ret Geometry
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContextSourceRegistration) GetLocationOk() (*Geometry, bool) {
	if o == nil || o.Location == nil {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *ContextSourceRegistration) HasLocation() bool {
	if o != nil && o.Location != nil {
		return true
	}

	return false
}

// SetLocation gets a reference to the given Geometry and assigns it to the Location field.
func (o *ContextSourceRegistration) SetLocation(v Geometry) {
	o.Location = &v
}

// GetObservationSpace returns the ObservationSpace field value if set, zero value otherwise.
func (o *ContextSourceRegistration) GetObservationSpace() Geometry {
	if o == nil || o.ObservationSpace == nil {
		var ret Geometry
		return ret
	}
	return *o.ObservationSpace
}

// GetObservationSpaceOk returns a tuple with the ObservationSpace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContextSourceRegistration) GetObservationSpaceOk() (*Geometry, bool) {
	if o == nil || o.ObservationSpace == nil {
		return nil, false
	}
	return o.ObservationSpace, true
}

// HasObservationSpace returns a boolean if a field has been set.
func (o *ContextSourceRegistration) HasObservationSpace() bool {
	if o != nil && o.ObservationSpace != nil {
		return true
	}

	return false
}

// SetObservationSpace gets a reference to the given Geometry and assigns it to the ObservationSpace field.
func (o *ContextSourceRegistration) SetObservationSpace(v Geometry) {
	o.ObservationSpace = &v
}

// GetOperationSpace returns the OperationSpace field value if set, zero value otherwise.
func (o *ContextSourceRegistration) GetOperationSpace() Geometry {
	if o == nil || o.OperationSpace == nil {
		var ret Geometry
		return ret
	}
	return *o.OperationSpace
}

// GetOperationSpaceOk returns a tuple with the OperationSpace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContextSourceRegistration) GetOperationSpaceOk() (*Geometry, bool) {
	if o == nil || o.OperationSpace == nil {
		return nil, false
	}
	return o.OperationSpace, true
}

// HasOperationSpace returns a boolean if a field has been set.
func (o *ContextSourceRegistration) HasOperationSpace() bool {
	if o != nil && o.OperationSpace != nil {
		return true
	}

	return false
}

// SetOperationSpace gets a reference to the given Geometry and assigns it to the OperationSpace field.
func (o *ContextSourceRegistration) SetOperationSpace(v Geometry) {
	o.OperationSpace = &v
}

// GetExpires returns the Expires field value if set, zero value otherwise.
func (o *ContextSourceRegistration) GetExpires() time.Time {
	if o == nil || o.Expires == nil {
		var ret time.Time
		return ret
	}
	return *o.Expires
}

// GetExpiresOk returns a tuple with the Expires field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContextSourceRegistration) GetExpiresOk() (*time.Time, bool) {
	if o == nil || o.Expires == nil {
		return nil, false
	}
	return o.Expires, true
}

// HasExpires returns a boolean if a field has been set.
func (o *ContextSourceRegistration) HasExpires() bool {
	if o != nil && o.Expires != nil {
		return true
	}

	return false
}

// SetExpires gets a reference to the given time.Time and assigns it to the Expires field.
func (o *ContextSourceRegistration) SetExpires(v time.Time) {
	o.Expires = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ContextSourceRegistration) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContextSourceRegistration) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ContextSourceRegistration) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ContextSourceRegistration) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ContextSourceRegistration) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContextSourceRegistration) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ContextSourceRegistration) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ContextSourceRegistration) SetDescription(v string) {
	o.Description = &v
}

// GetEndpoint returns the Endpoint field value
func (o *ContextSourceRegistration) GetEndpoint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Endpoint
}

// GetEndpointOk returns a tuple with the Endpoint field value
// and a boolean to check if the value has been set.
func (o *ContextSourceRegistration) GetEndpointOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Endpoint, true
}

// SetEndpoint sets field value
func (o *ContextSourceRegistration) SetEndpoint(v string) {
	o.Endpoint = v
}

// GetId returns the Id field value
func (o *ContextSourceRegistration) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ContextSourceRegistration) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ContextSourceRegistration) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *ContextSourceRegistration) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ContextSourceRegistration) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ContextSourceRegistration) SetType(v string) {
	o.Type = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ContextSourceRegistration) GetCreatedAt() time.Time {
	if o == nil || o.CreatedAt == nil {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContextSourceRegistration) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ContextSourceRegistration) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *ContextSourceRegistration) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetModifiedAt returns the ModifiedAt field value if set, zero value otherwise.
func (o *ContextSourceRegistration) GetModifiedAt() time.Time {
	if o == nil || o.ModifiedAt == nil {
		var ret time.Time
		return ret
	}
	return *o.ModifiedAt
}

// GetModifiedAtOk returns a tuple with the ModifiedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContextSourceRegistration) GetModifiedAtOk() (*time.Time, bool) {
	if o == nil || o.ModifiedAt == nil {
		return nil, false
	}
	return o.ModifiedAt, true
}

// HasModifiedAt returns a boolean if a field has been set.
func (o *ContextSourceRegistration) HasModifiedAt() bool {
	if o != nil && o.ModifiedAt != nil {
		return true
	}

	return false
}

// SetModifiedAt gets a reference to the given time.Time and assigns it to the ModifiedAt field.
func (o *ContextSourceRegistration) SetModifiedAt(v time.Time) {
	o.ModifiedAt = &v
}

func (o ContextSourceRegistration) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Context != nil {
		toSerialize["@context"] = o.Context
	}
	if true {
		toSerialize["information"] = o.Information
	}
	if o.ObservationInterval != nil {
		toSerialize["observationInterval"] = o.ObservationInterval
	}
	if o.ManagementInterval != nil {
		toSerialize["managementInterval"] = o.ManagementInterval
	}
	if o.Location != nil {
		toSerialize["location"] = o.Location
	}
	if o.ObservationSpace != nil {
		toSerialize["observationSpace"] = o.ObservationSpace
	}
	if o.OperationSpace != nil {
		toSerialize["operationSpace"] = o.OperationSpace
	}
	if o.Expires != nil {
		toSerialize["expires"] = o.Expires
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if true {
		toSerialize["endpoint"] = o.Endpoint
	}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["type"] = o.Type
	}
	if o.CreatedAt != nil {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if o.ModifiedAt != nil {
		toSerialize["modifiedAt"] = o.ModifiedAt
	}
	return json.Marshal(toSerialize)
}

type NullableContextSourceRegistration struct {
	value *ContextSourceRegistration
	isSet bool
}

func (v NullableContextSourceRegistration) Get() *ContextSourceRegistration {
	return v.value
}

func (v *NullableContextSourceRegistration) Set(val *ContextSourceRegistration) {
	v.value = val
	v.isSet = true
}

func (v NullableContextSourceRegistration) IsSet() bool {
	return v.isSet
}

func (v *NullableContextSourceRegistration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContextSourceRegistration(val *ContextSourceRegistration) *NullableContextSourceRegistration {
	return &NullableContextSourceRegistration{value: val, isSet: true}
}

func (v NullableContextSourceRegistration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContextSourceRegistration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


