/*
ETSI ISG CIM / NGSI-LD API

This OAS file describes the NGSI-LD API defined by the ETSI ISG CIM group. This Cross-domain Context Information Management API allows to provide, consume and subscribe to context information in multiple scenarios and involving multiple stakeholders

API version: latest
Contact: NGSI-LD@etsi.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// EntityTemporal struct for EntityTemporal
type EntityTemporal struct {
	Context map[string]interface{} `json:"@context,omitempty"`
	Location []GeoProperty `json:"location,omitempty"`
	ObservationSpace []GeoProperty `json:"observationSpace,omitempty"`
	OperationSpace []GeoProperty `json:"operationSpace,omitempty"`
	Id string `json:"id"`
	// NGSI-LD Name
	Type string `json:"type"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	ModifiedAt *time.Time `json:"modifiedAt,omitempty"`
}

// NewEntityTemporal instantiates a new EntityTemporal object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntityTemporal(id string, type_ string) *EntityTemporal {
	this := EntityTemporal{}
	this.Id = id
	this.Type = type_
	return &this
}

// NewEntityTemporalWithDefaults instantiates a new EntityTemporal object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntityTemporalWithDefaults() *EntityTemporal {
	this := EntityTemporal{}
	return &this
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *EntityTemporal) GetContext() map[string]interface{} {
	if o == nil || o.Context == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityTemporal) GetContextOk() (map[string]interface{}, bool) {
	if o == nil || o.Context == nil {
		return nil, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *EntityTemporal) HasContext() bool {
	if o != nil && o.Context != nil {
		return true
	}

	return false
}

// SetContext gets a reference to the given map[string]interface{} and assigns it to the Context field.
func (o *EntityTemporal) SetContext(v map[string]interface{}) {
	o.Context = v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *EntityTemporal) GetLocation() []GeoProperty {
	if o == nil || o.Location == nil {
		var ret []GeoProperty
		return ret
	}
	return o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityTemporal) GetLocationOk() ([]GeoProperty, bool) {
	if o == nil || o.Location == nil {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *EntityTemporal) HasLocation() bool {
	if o != nil && o.Location != nil {
		return true
	}

	return false
}

// SetLocation gets a reference to the given []GeoProperty and assigns it to the Location field.
func (o *EntityTemporal) SetLocation(v []GeoProperty) {
	o.Location = v
}

// GetObservationSpace returns the ObservationSpace field value if set, zero value otherwise.
func (o *EntityTemporal) GetObservationSpace() []GeoProperty {
	if o == nil || o.ObservationSpace == nil {
		var ret []GeoProperty
		return ret
	}
	return o.ObservationSpace
}

// GetObservationSpaceOk returns a tuple with the ObservationSpace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityTemporal) GetObservationSpaceOk() ([]GeoProperty, bool) {
	if o == nil || o.ObservationSpace == nil {
		return nil, false
	}
	return o.ObservationSpace, true
}

// HasObservationSpace returns a boolean if a field has been set.
func (o *EntityTemporal) HasObservationSpace() bool {
	if o != nil && o.ObservationSpace != nil {
		return true
	}

	return false
}

// SetObservationSpace gets a reference to the given []GeoProperty and assigns it to the ObservationSpace field.
func (o *EntityTemporal) SetObservationSpace(v []GeoProperty) {
	o.ObservationSpace = v
}

// GetOperationSpace returns the OperationSpace field value if set, zero value otherwise.
func (o *EntityTemporal) GetOperationSpace() []GeoProperty {
	if o == nil || o.OperationSpace == nil {
		var ret []GeoProperty
		return ret
	}
	return o.OperationSpace
}

// GetOperationSpaceOk returns a tuple with the OperationSpace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityTemporal) GetOperationSpaceOk() ([]GeoProperty, bool) {
	if o == nil || o.OperationSpace == nil {
		return nil, false
	}
	return o.OperationSpace, true
}

// HasOperationSpace returns a boolean if a field has been set.
func (o *EntityTemporal) HasOperationSpace() bool {
	if o != nil && o.OperationSpace != nil {
		return true
	}

	return false
}

// SetOperationSpace gets a reference to the given []GeoProperty and assigns it to the OperationSpace field.
func (o *EntityTemporal) SetOperationSpace(v []GeoProperty) {
	o.OperationSpace = v
}

// GetId returns the Id field value
func (o *EntityTemporal) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *EntityTemporal) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *EntityTemporal) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *EntityTemporal) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *EntityTemporal) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *EntityTemporal) SetType(v string) {
	o.Type = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *EntityTemporal) GetCreatedAt() time.Time {
	if o == nil || o.CreatedAt == nil {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityTemporal) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *EntityTemporal) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *EntityTemporal) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetModifiedAt returns the ModifiedAt field value if set, zero value otherwise.
func (o *EntityTemporal) GetModifiedAt() time.Time {
	if o == nil || o.ModifiedAt == nil {
		var ret time.Time
		return ret
	}
	return *o.ModifiedAt
}

// GetModifiedAtOk returns a tuple with the ModifiedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityTemporal) GetModifiedAtOk() (*time.Time, bool) {
	if o == nil || o.ModifiedAt == nil {
		return nil, false
	}
	return o.ModifiedAt, true
}

// HasModifiedAt returns a boolean if a field has been set.
func (o *EntityTemporal) HasModifiedAt() bool {
	if o != nil && o.ModifiedAt != nil {
		return true
	}

	return false
}

// SetModifiedAt gets a reference to the given time.Time and assigns it to the ModifiedAt field.
func (o *EntityTemporal) SetModifiedAt(v time.Time) {
	o.ModifiedAt = &v
}

func (o EntityTemporal) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Context != nil {
		toSerialize["@context"] = o.Context
	}
	if o.Location != nil {
		toSerialize["location"] = o.Location
	}
	if o.ObservationSpace != nil {
		toSerialize["observationSpace"] = o.ObservationSpace
	}
	if o.OperationSpace != nil {
		toSerialize["operationSpace"] = o.OperationSpace
	}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["type"] = o.Type
	}
	if o.CreatedAt != nil {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if o.ModifiedAt != nil {
		toSerialize["modifiedAt"] = o.ModifiedAt
	}
	return json.Marshal(toSerialize)
}

type NullableEntityTemporal struct {
	value *EntityTemporal
	isSet bool
}

func (v NullableEntityTemporal) Get() *EntityTemporal {
	return v.value
}

func (v *NullableEntityTemporal) Set(val *EntityTemporal) {
	v.value = val
	v.isSet = true
}

func (v NullableEntityTemporal) IsSet() bool {
	return v.isSet
}

func (v *NullableEntityTemporal) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntityTemporal(val *EntityTemporal) *NullableEntityTemporal {
	return &NullableEntityTemporal{value: val, isSet: true}
}

func (v NullableEntityTemporal) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntityTemporal) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


