/*
ETSI ISG CIM / NGSI-LD API

This OAS file describes the NGSI-LD API defined by the ETSI ISG CIM group. This Cross-domain Context Information Management API allows to provide, consume and subscribe to context information in multiple scenarios and involving multiple stakeholders

API version: latest
Contact: NGSI-LD@etsi.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// EntityTemporalFragment struct for EntityTemporalFragment
type EntityTemporalFragment struct {
	Context map[string]interface{} `json:"@context,omitempty"`
	Location []GeoProperty `json:"location,omitempty"`
	ObservationSpace []GeoProperty `json:"observationSpace,omitempty"`
	OperationSpace []GeoProperty `json:"operationSpace,omitempty"`
	Id *string `json:"id,omitempty"`
	// NGSI-LD Name
	Type *string `json:"type,omitempty"`
}

// NewEntityTemporalFragment instantiates a new EntityTemporalFragment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntityTemporalFragment() *EntityTemporalFragment {
	this := EntityTemporalFragment{}
	return &this
}

// NewEntityTemporalFragmentWithDefaults instantiates a new EntityTemporalFragment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntityTemporalFragmentWithDefaults() *EntityTemporalFragment {
	this := EntityTemporalFragment{}
	return &this
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *EntityTemporalFragment) GetContext() map[string]interface{} {
	if o == nil || o.Context == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityTemporalFragment) GetContextOk() (map[string]interface{}, bool) {
	if o == nil || o.Context == nil {
		return nil, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *EntityTemporalFragment) HasContext() bool {
	if o != nil && o.Context != nil {
		return true
	}

	return false
}

// SetContext gets a reference to the given map[string]interface{} and assigns it to the Context field.
func (o *EntityTemporalFragment) SetContext(v map[string]interface{}) {
	o.Context = v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *EntityTemporalFragment) GetLocation() []GeoProperty {
	if o == nil || o.Location == nil {
		var ret []GeoProperty
		return ret
	}
	return o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityTemporalFragment) GetLocationOk() ([]GeoProperty, bool) {
	if o == nil || o.Location == nil {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *EntityTemporalFragment) HasLocation() bool {
	if o != nil && o.Location != nil {
		return true
	}

	return false
}

// SetLocation gets a reference to the given []GeoProperty and assigns it to the Location field.
func (o *EntityTemporalFragment) SetLocation(v []GeoProperty) {
	o.Location = v
}

// GetObservationSpace returns the ObservationSpace field value if set, zero value otherwise.
func (o *EntityTemporalFragment) GetObservationSpace() []GeoProperty {
	if o == nil || o.ObservationSpace == nil {
		var ret []GeoProperty
		return ret
	}
	return o.ObservationSpace
}

// GetObservationSpaceOk returns a tuple with the ObservationSpace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityTemporalFragment) GetObservationSpaceOk() ([]GeoProperty, bool) {
	if o == nil || o.ObservationSpace == nil {
		return nil, false
	}
	return o.ObservationSpace, true
}

// HasObservationSpace returns a boolean if a field has been set.
func (o *EntityTemporalFragment) HasObservationSpace() bool {
	if o != nil && o.ObservationSpace != nil {
		return true
	}

	return false
}

// SetObservationSpace gets a reference to the given []GeoProperty and assigns it to the ObservationSpace field.
func (o *EntityTemporalFragment) SetObservationSpace(v []GeoProperty) {
	o.ObservationSpace = v
}

// GetOperationSpace returns the OperationSpace field value if set, zero value otherwise.
func (o *EntityTemporalFragment) GetOperationSpace() []GeoProperty {
	if o == nil || o.OperationSpace == nil {
		var ret []GeoProperty
		return ret
	}
	return o.OperationSpace
}

// GetOperationSpaceOk returns a tuple with the OperationSpace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityTemporalFragment) GetOperationSpaceOk() ([]GeoProperty, bool) {
	if o == nil || o.OperationSpace == nil {
		return nil, false
	}
	return o.OperationSpace, true
}

// HasOperationSpace returns a boolean if a field has been set.
func (o *EntityTemporalFragment) HasOperationSpace() bool {
	if o != nil && o.OperationSpace != nil {
		return true
	}

	return false
}

// SetOperationSpace gets a reference to the given []GeoProperty and assigns it to the OperationSpace field.
func (o *EntityTemporalFragment) SetOperationSpace(v []GeoProperty) {
	o.OperationSpace = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *EntityTemporalFragment) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityTemporalFragment) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *EntityTemporalFragment) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *EntityTemporalFragment) SetId(v string) {
	o.Id = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *EntityTemporalFragment) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityTemporalFragment) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *EntityTemporalFragment) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *EntityTemporalFragment) SetType(v string) {
	o.Type = &v
}

func (o EntityTemporalFragment) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Context != nil {
		toSerialize["@context"] = o.Context
	}
	if o.Location != nil {
		toSerialize["location"] = o.Location
	}
	if o.ObservationSpace != nil {
		toSerialize["observationSpace"] = o.ObservationSpace
	}
	if o.OperationSpace != nil {
		toSerialize["operationSpace"] = o.OperationSpace
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableEntityTemporalFragment struct {
	value *EntityTemporalFragment
	isSet bool
}

func (v NullableEntityTemporalFragment) Get() *EntityTemporalFragment {
	return v.value
}

func (v *NullableEntityTemporalFragment) Set(val *EntityTemporalFragment) {
	v.value = val
	v.isSet = true
}

func (v NullableEntityTemporalFragment) IsSet() bool {
	return v.isSet
}

func (v *NullableEntityTemporalFragment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntityTemporalFragment(val *EntityTemporalFragment) *NullableEntityTemporalFragment {
	return &NullableEntityTemporalFragment{value: val, isSet: true}
}

func (v NullableEntityTemporalFragment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntityTemporalFragment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


